name: Docker Image CI

on:
  push:
    branches: [main]
    paths:
      - "apps/bot"
      - "packages"
      - "*.*"

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{github.repository}}/bot:latest -f apps/bot/Dockerfile .

      - name: Push Docker image
        run: docker push ghcr.io/${{github.repository}}/bot:latest
